export const musicData = [
  {
    uid: "1",
    album_name: "Ethereal Dreams",
    band_name: "Azure Horizons",
    song_name: "Whispers in the Mist",
    ratings: 4.2,
    duration: "3:45",
    image: "https://example.com/ethereal_dreams.jpg",
  },
  {
    uid: "2",
    album_name: "Neon Nights",
    band_name: "Synthwave Sensation",
    song_name: "Midnight Drive",
    ratings: 4.5,
    duration: "4:20",
    image: "https://example.com/neon_nights.jpg",
  },
  {
    uid: "3",
    album_name: "Sunset Serenade",
    band_name: "Golden Groove",
    song_name: "Summer Breeze",
    ratings: 4.8,
    duration: "5:10",
    image: "https://example.com/sunset_serenade.jpg",
  },
  {
    uid: "4",
    album_name: "Electric Echoes",
    band_name: "Voltage Vibes",
    song_name: "Circuitry Symphony",
    ratings: 4.3,
    duration: "3:55",
    image: "https://example.com/electric_echoes.jpg",
  },
  {
    uid: "5",
    album_name: "Moonlit Melodies",
    band_name: "Lunar Lullabies",
    song_name: "Starry Night Sonata",
    ratings: 4.6,
    duration: "4:40",
    image: "https://example.com/moonlit_melodies.jpg",
  },
  {
    uid: "6",
    album_name: "Retro Revival",
    band_name: "Vintage Vibes",
    song_name: "Old School Groove",
    ratings: 4.0,
    duration: "3:30",
    image: "https://example.com/retro_revival.jpg",
  },
  {
    uid: "7",
    album_name: "Crystal Clear",
    band_name: "Sonic Solace",
    song_name: "Glass Symphony",
    ratings: 4.7,
    duration: "4:55",
    image: "https://example.com/crystal_clear.jpg",
  },
  {
    uid: "8",
    album_name: "Urban Utopia",
    band_name: "City Slickers",
    song_name: "Metropolis Beats",
    ratings: 4.4,
    duration: "4:05",
    image: "https://example.com/urban_utopia.jpg",
  },
  {
    uid: "9",
    album_name: "Mystic Memories",
    band_name: "Enigmatic Ensemble",
    song_name: "Echoes of Eternity",
    ratings: 4.9,
    duration: "5:30",
    image: "https://example.com/mystic_memories.jpg",
  },
  {
    uid: "10",
    album_name: "Astral Ascendance",
    band_name: "Celestial Soundscape",
    song_name: "Cosmic Harmony",
    ratings: 4.1,
    duration: "3:35",
    image: "https://example.com/astral_ascendance.jpg",
  },
  {
    uid: "11",
    album_name: "Oceanic Overture",
    band_name: "Maritime Melodies",
    song_name: "Siren's Serenade",
    ratings: 4.6,
    duration: "4:45",
    image: "https://example.com/oceanic_overture.jpg",
  },
  {
    uid: "12",
    album_name: "Jungle Jams",
    band_name: "Wild Rhythms",
    song_name: "Amazon Adventure",
    ratings: 4.3,
    duration: "4:00",
    image: "https://example.com/jungle_jams.jpg",
  },
  {
    uid: "13",
    album_name: "Echo Chamber",
    band_name: "Acoustic Ambiance",
    song_name: "Resonance Reverie",
    ratings: 4.8,
    duration: "5:05",
    image: "https://example.com/echo_chamber.jpg",
  },
  {
    uid: "14",
    album_name: "Frosty Fugue",
    band_name: "Winter Waltz",
    song_name: "Snowflake Sonata",
    ratings: 4.5,
    duration: "4:25",
    image: "https://example.com/frosty_fugue.jpg",
  },
  {
    uid: "15",
    album_name: "Fiery Fusion",
    band_name: "Inferno Ensemble",
    song_name: "Blaze Breakdown",
    ratings: 4.2,
    duration: "3:50",
    image: "https://example.com/fiery_fusion.jpg",
  },
  {
    uid: "16",
    album_name: "Dreamy Duet",
    band_name: "Harmonic Harmony",
    song_name: "Melodic Mirage",
    ratings: 4.7,
    duration: "4:50",
    image: "https://example.com/dreamy_duet.jpg",
  },
  {
    uid: "17",
    album_name: "Techno Trance",
    band_name: "Synaptic Symphony",
    song_name: "Cybernetic Rhythm",
    ratings: 4.4,
    duration: "4:10",
    image: "https://example.com/techno_trance.jpg",
  },
  {
    uid: "18",
    album_name: "Fantasy Fables",
    band_name: "Mythical Melodies",
    song_name: "Enchanted Expedition",
    ratings: 4.9,
    duration: "5:35",
    image: "https://example.com/fantasy_fables.jpg",
  },
  {
    uid: "19",
    album_name: "Galactic Groove",
    band_name: "Cosmic Cadence",
    song_name: "Starlight Symphony",
    ratings: 4.0,
    duration: "3:25",
    image: "https://example.com/galactic_groove.jpg",
  },
  {
    uid: "20",
    album_name: "Soothing Serenade",
    band_name: "Tranquil Tones",
    song_name: "Peaceful Prelude",
    ratings: 4.6,
  },
  ,
  {
    uid: "21",
    album_name: "Mystical Medley",
    band_name: "Enchanted Ensemble",
    song_name: "Magical Melodies",
    ratings: 4.3,
    duration: "4:15",
    image: "https://example.com/mystical_medley.jpg",
  },
  {
    uid: "22",
    album_name: "Groovy Galaxy",
    band_name: "Interstellar Intonations",
    song_name: "Cosmic Disco",
    ratings: 4.1,
    duration: "4:05",
    image: "https://example.com/groovy_galaxy.jpg",
  },
  {
    uid: "23",
    album_name: "Silent Symphony",
    band_name: "Whispering Winds",
    song_name: "Serenade of Solitude",
    ratings: 4.8,
    duration: "5:15",
    image: "https://example.com/silent_symphony.jpg",
  },
  {
    uid: "24",
    album_name: "Electric Eden",
    band_name: "Neon Nectar",
    song_name: "Technicolor Dream",
    ratings: 4.4,
    duration: "4:20",
    image: "https://example.com/electric_eden.jpg",
  },
  {
    uid: "25",
    album_name: "Crystal Caverns",
    band_name: "Echoic Ensemble",
    song_name: "Quartz Quartet",
    ratings: 4.5,
    duration: "4:30",
    image: "https://example.com/crystal_caverns.jpg",
  },
  {
    uid: "26",
    album_name: "Jazz Jamboree",
    band_name: "Swinging Sensations",
    song_name: "Smooth Sailing",
    ratings: 4.3,
    duration: "4:10",
    image: "https://example.com/jazz_jamboree.jpg",
  },
  {
    uid: "27",
    album_name: "Midnight Melancholy",
    band_name: "Nocturnal Notes",
    song_name: "Moonlit Sonata",
    ratings: 4.6,
    duration: "4:40",
    image: "https://example.com/midnight_melancholy.jpg",
  },
  {
    uid: "28",
    album_name: "Tropical Tango",
    band_name: "Island Harmonies",
    song_name: "Sunset Samba",
    ratings: 4.2,
    duration: "3:55",
    image: "https://example.com/tropical_tango.jpg",
  },
  {
    uid: "29",
    album_name: "Symphonic Sunset",
    band_name: "Dusk Descendants",
    song_name: "Twilight Overture",
    ratings: 4.7,
    duration: "4:55",
    image: "https://example.com/symphonic_sunset.jpg",
  },
  {
    uid: "30",
    album_name: "Melodic Mirage",
    band_name: "Harmonic Hues",
    song_name: "Chromatic Cantata",
    ratings: 4.9,
    duration: "5:25",
    image: "https://example.com/melodic_mirage.jpg",
  },
];
