import { Montserrat } from "next/font/google";
import "./globals.css";
import TanstackProvider from "./_libs/components/providers/TanstackProvider";
import Navbar from "./_libs/components/ui/Navbar";

const font = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Beats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main className="bg-black">
          <TanstackProvider>
            <Navbar />
            {children}
          </TanstackProvider>
        </main>
      </body>
    </html>
  );
}
